const languages = new Map([
   ['agda', 'Agda'],
   ['bf', 'BF'],
   ['c', 'C'],
   ['cfml', 'CFML'],
   ['clojure', 'Clojure'],
   ['cobol', 'COBOL'],
   ['coffeescript', 'CoffeeScript'],
   ['commonlisp', 'CommonLisp'],
   ['coq', 'Coq'],
   ['cpp', 'C++'],
   ['crystal', 'Crystal'],
   ['csharp', 'C#'],
   ['dart', 'Dart'],
   ['elixir', 'Elixir'],
   ['elm', 'Elm'],
   ['erlang', 'Erlang'],
   ['factor', 'Factor'],
   ['forth', 'Forth'],
   ['fortran', 'Fortran'],
   ['fsharp', 'F#'],
   ['go', 'Go'],
   ['groovy', 'Groovy'],
   ['haskell', 'Haskell'],
   ['haxe', 'Haxe'],
   ['idris', 'Idris'],
   ['java', 'Java'],
   ['javascript', 'JavaScript'],
   ['julia', 'Julia'],
   ['kotlin', 'Kotlin'],
   ['lean', 'Lean'],
   ['lua', 'Lua'],
   ['nasm', 'NASM'],
   ['nim', 'Nim'],
   ['objc', 'Objective-C'],
   ['ocaml', 'OCaml'],
   ['pascal', 'Pascal'],
   ['perl', 'Perl'],
   ['php', 'PHP'],
   ['powershell', 'PowerShell'],
   ['prolog', 'Prolog'],
   ['purescript', 'PureScript'],
   ['python', 'Python'],
   ['r', 'R'],
   ['racket', 'Racket'],
   ['raku', 'Raku'],
   ['reason', 'Reason'],
   ['ruby', 'Ruby'],
   ['rust', 'Rust'],
   ['scala', 'Scala'],
   ['shell', 'Shell'],
   ['solidity', 'Solidity'],
   ['sql', 'SQL'],
   ['swift', 'Swift'],
   ['typescript', 'TypeScript'],
   ['vb', 'VB'],
])

export function languageFormat(languageName: string): string {
   return languages.get(languageName) ?? languageName
}
